<a href="https://colab.research.google.com/github/Muskan2320/Data-Science/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices.

In [2]:
import numpy as np

# Array

The array object in NumPy is called ndarray

In [ ]:
a = np.array([1,2])             # Create 1D array. It can have multi-dimensional arrays also.

print(a)
print(type(a))

[1 2]
<class 'numpy.ndarray'>


# Dimension of array

In [ ]:
a = np.array([[1, 3, 6], [5, 3, 2], [2, 6, 3]])

print(a.ndim)                                              # It return dimensions of an array
print(a)

2
[[1 3 6]
 [5 3 2]
 [2 6 3]]


# Shape of array

In [ ]:
a.shape

(3, 3)

# Indexing and Slicing

In [ ]:
a = np.array([[1, 3, 6], [5, 3, 2], [2, 6, 3], [5, 9, 6], [7, 5, 6]])   # A 2D array

print(a[0][1])                                                          # Indexing starts from zero
print(a[1])                                                             # print entire row

print(a[:, 2])                                                          # print column third as index starts from 0
print(a[0:3, 1])
print("\n Array: \n", a)

3
[5 3 2]
[6 2 3 6 6]
[3 3 6]

 Array: 
 [[1 3 6]
 [5 3 2]
 [2 6 3]
 [5 9 6]
 [7 5 6]]


# Iterate in Array

In [ ]:
a = np.array([[1, 3, 6], [5, 3, 2], [2, 6, 3], [5, 9, 6], [7, 5, 6]])

for x in a:
  print(x)

[1 3 6]
[5 3 2]
[2 6 3]
[5 9 6]
[7 5 6]


In [ ]:
a = np.array([[1, 3, 6], [5, 3, 2], [2, 6, 3], [5, 9, 6], [7, 5, 6]])

for x in a:
  for y in x:
    print(y, end = " ")

  print()

1 3 6 
5 3 2 
2 6 3 
5 9 6 
7 5 6 


# Comparison operation

It is frequently used in manipulation and image processing

In [ ]:
a = np.array([[1, 3, 6], [5, 3, 2], [2, 6, 3], [5, 9, 6], [7, 5, 6]])

b = a > 3                                                                     # b is a list containing True and False corresponding to each element in a as per comparison

print(b)
print(a[b])                                                                   # prints element greater than 3

[[False False  True]
 [ True False False]
 [False  True False]
 [ True  True  True]
 [ True  True  True]]
[6 5 6 5 9 6 7 5 6]


In [ ]:
# Similarly, other operations can be performed

print(a[a<2])
print(a[a%2 == 0])

[1]
[6 2 2 6 6 6]


# Producing sequence

In [ ]:
arr = np.arange(10, 18)                     # It creates 1D array from 10 to 17 as 18 is excluded
arr

array([10, 11, 12, 13, 14, 15, 16, 17])

In [ ]:
arr = np.arange(1, 10, 2)                   # np.arange(start, stop, step)
arr

array([1, 3, 5, 7, 9])

# Reshaping array

In [ ]:
# Reshape function takes 2 arguements i.e. number of rows and columns
arr = np.arange(1, 10).reshape(3,3)         # sequence produce 9 elements so product of number of rows and columns should be also 9
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Sorting Array

In [ ]:
a = np.array([[1, 3, 6], [5, 3, 2], [5, 9, 6], [2, 6, 3], [7, 5, 6]])

a_sort = np.sort(a)                                                          # It sort the each row of array
print(a_sort)

[[1 3 6]
 [2 3 5]
 [5 6 9]
 [2 3 6]
 [5 6 7]]


# Types of matrix

Numpy can produce different types of matrix like identity matrix, a matrix having all element zero, a matrix having all element one.

In [3]:
ide = np.eye(3)                        # Gives idnetity matrix of given size
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
ide = np.eye(3,2)
ide

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [5]:
np.zeros((2,4))                         # Gives matrix with all elements 0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones((5,5))                           # Gives matrix with all elements 1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# Matrix operations

In [8]:
a = np.eye(3)
b = np.array([[2, 4, 6], [5, 6, 3], [8, 5, 2]])

In [20]:
# Addition

sum = a + b
sum

array([[3., 4., 6.],
       [5., 7., 3.],
       [8., 5., 3.]])

In [19]:
# Subtraction

sub = a - b
sub

array([[-1., -4., -6.],
       [-5., -5., -3.],
       [-8., -5., -1.]])

In [22]:
# Normal matrix multiplication

nmul = b @ sum
nmul

array([[74., 66., 42.],
       [69., 77., 57.],
       [65., 77., 69.]])

In [23]:
# Point-wise multiplication

pmul = a * b
pmul

array([[2., 0., 0.],
       [0., 6., 0.],
       [0., 0., 2.]])

In [25]:
b[2] = b[2] * [0, 0, 0]                # changing one row of matrix using point-wise multiplication
b

array([[2, 4, 6],
       [5, 6, 3],
       [0, 0, 0]])

In [26]:
b[b>5] = 0                             # changing all elements to zero which are greater than 5
b

array([[2, 4, 0],
       [5, 0, 3],
       [0, 0, 0]])

In [28]:
# Dot product - Similiar to dot product of vectors

arr = np.array([[2., 0., 0.], [0., 6., 0.], [0., 0., 2.]])
dot = np.dot(arr, b)
dot

array([[ 4.,  8.,  0.],
       [30.,  0., 18.],
       [ 0.,  0.,  0.]])

In [29]:
# Matrix transpose

tran = dot.T
tran

array([[ 4., 30.,  0.],
       [ 8.,  0.,  0.],
       [ 0., 18.,  0.]])